        <!-- @installer: Navbar Top -->
        <nav class="topbar navbar navbar-dark bg-dark">
            <div class="container d-flex align-items-center justify-content-between w-100">
                <a class="navbar-brand d-flex align-items-center" href="{{ $this->path('start') }}">
                    <img src="{{ $this->asset('images/logo.png') }}" width="38" height="40" alt="{{ $this->trans('installer.engine') }}">
                </a>
                <ul class="navbar-nav d-flex flex-row gap-3 flex-grow-1 justify-content-start">
                    <li class="nav-item">
                        <a class="nav-link text-truncate dbm-nav-max-width{{ $this->isActive('index', 'active', '') }}" href="{{ $this->path() }}">{{ $this->trans('installer.navbar.home') }}</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link disabled text-truncate dbm-nav-max-width" tabindex="-1" aria-disabled="true">{{ $this->trans('installer.navbar.extensions') }}</a>
                    </li>
                </ul>
                <div class="ms-3">
                    <a href="https://dbm.org.pl/tworzenie/dbmframework" target="_blank" class="btn btn-outline-warning">{{ $this->trans('installer.navbar.download') }}</a>
                </div>
            </div>
        </nav>
