    <!-- Footer -->
    <footer class="footer mt-auto py-3 bg-light text-center">
        <div class="container">
            <span class="text-muted">&copy; 2021-{{ date('Y') }} <a href="https://dbm.org.pl/tworzenie/dbmframework" class="link-secondary text-decoration-none" target="_blank">DbM Framework</a> Design by Malina, All rights reserved.</span>
        </div>
    </footer>
	<!-- JavaScript -->
    <script src="{{ $this->asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
