    <!-- Footer -->
    <footer class="footer mt-auto py-3 bg-light text-center">
        <div class="container">
            <span class="text-muted">&copy; 2021-{{ date('Y') }} <a href="https://dybem.com/" class="link-dark text-decoration-none" target="_blank">Dybem</a> &bull; DBM Framework &bull; All rights reserved.</span>
        </div>
    </footer>
	<!-- JavaScript -->
    <script src="{{ $this->asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
